version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - python
    networks:
      - local

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=christestpass           # Set demo password for the 'elastic' user
      - xpack.security.enabled=true              # Enable security
      - xpack.security.http.ssl.enabled=false    # Disable HTTPS for local testing
    ports:
      - "9200:9200"                              # Expose Elasticsearch on port 9200
    networks:
      - local                                    # Connect to the 'local' network

  python:
    build: ./python
    environment:
      ELASTIC_PASSWORD: christestpass
    depends_on:
      elasticsearch:
        condition: service_started
    networks:
      - local

# Create a network for local development
networks:
  local:
    driver: bridge