version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=christestpass           # Set demo password for the 'elastic' user
      - xpack.security.enabled=true              # Enable security
      - xpack.security.http.ssl.enabled=false    # Disable HTTPS for local testing
    ports:
      - "9200:9200"                              # Expose Elasticsearch on port 9200
    networks:
      - local                                    # Connect to the 'local' network

# Create a network for local development
networks:
  local:
    driver: bridge